blog/urls.py
"Main project url file"
from django.urls import path
from . import views

app_name = 'BLOG'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('search/', views.search, name='search'),
    path('news/', views.NewsPage, name='NewsPage'),
    path('edit/', views.UserProfile.as_view(), name='edit_profile'),
    path('create/', views.CreatePost.as_view(), name='CreatePost'),
    path('<slug:post>/', views.post_detail, name='post_detail'),
    path('update/<slug>/', views.EditPost.as_view(), name='EditPost'),
    path('delete/<slug>/', views.DeletePost.as_view(), name='DeletePost'),
    path('like/<slug:slug>', views.LikeView, name='like_post'),
    path('category/<category>/', views.CategoryView.as_view(), name='category')
]

falloutinator/urls.py
"Main project url file"
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('blog.urls', namespace='BLOG')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en" class="h-100">
{% load static %}

<head>
    <!-- Meta Tags -->
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Fallout blog for hardcore fans wanting to keep the vaults, weapons and wasteland alive and kicking, level up with us and explore a nuclear winter together">

    <!-- CSS Tags -->
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Arimo&family=Merriweather:wght@300&display=swap" rel="stylesheet">

    <title>Falloutinator | {% block title %}Home{% endblock %}</title>
</head>
<body>
  <!--Navigation bar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'BLOG:homepage' %}">Falloutinator</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'BLOG:NewsPage' %}">News</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
              </a>
              <div class="dropdown-menu">
                {% for categories in categorydropdown1 %}
                <a href="/category/{{ categories.name }}" class="dropdown-item">
                  {{ categories.name}}
                </a>
                {% endfor %}
              </div>
            </li>
            <li class="nav-item dropdown">          
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
              </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% if user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'BLOG:CreatePost' %}">Create Post</a>
                    <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
                  {% else %}
                    <a class="dropdown-item" href="{% url 'account_signup' %}">Register</a>
                    <a class="dropdown-item" href="{% url 'account_login' %}">Login</a>
                  {% endif %}
                  <a class="dropdown-item" href="{% url 'BLOG:edit_profile' %}">Contact</a>

                </div>
            </li>
          </ul>
            <form class="form-inline my-2 my-lg-0 search-bar-form" action="{% url 'BLOG:search' %}" method="get">
              <input required name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <!--Main content block to inject the content from each page-->

      <div class="container mt-4">
        {% block content %}
        {% endblock %}
      </div>

      <!--Footer Content-->
      <footer id="foot-bar" class=" footer sticky-bottom navbar-dark bg-primary mt-4 ">
        <a href="https://github.com/Benjamin-Joe" rel="noopener" target="_blank">
          <p id="foot-text">Content By Benjamin Joe</p>
        </a>
      </footer>

          <!-- Script Tags -->
          <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
          <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
          <script src="https://kit.fontawesome.com/fb3ce16b7a.js" crossorigin="anonymous"></script>
</body>
</html>

templates/category.html
{% extends "base.html" %}

<title>Falloutinator | {% block title %}{{ categorylist.cat}}{% endblock %}</title>

{% block content %}
<h1 class="text-center cat-title">
    Category: 
    {{ categorylist.cat }}
</h1>

<div class="container">

    <div class="row">
        {% for post in categorylist.posts %}
                <div class="col-lg-4 index-card">
                  {% if "placeholder" in post.post_image.url %}
                  <img class="rounded-circle index-img" src="https://res.cloudinary.com/benaldo66/image/upload/v1642635685/placeholder_lpvbw2.jpg" alt="Lazer background image with walls" width="140" height="140">
                  {% else %}
                  <img class="rounded-circle index-img" src="{{ post.post_image.url }}" alt="" width="140" height="140">
                  {% endif %}

                  <h2>{{ post.title|title }}</h2>
                  <p class="index-content">{{ post.content|striptags|slice:25}}...</p>
                  <p><small class="index-info">Written By: {{ post.author }} <br>
                  {{ post.created_on }} <br> {{ post.category }}</small></p>
                  <p><a class="btn btn-primary cat-btn" href="{{ post.get_absolute_url }}" role="button">View Post</a></p>
                </div>
            {% empty %}
            <h3 class="no-category">No Posts Under This Category Yet!</h3>
            <img class="no-category-image" src="https://res.cloudinary.com/benaldo66/image/upload/w_1000,ar_16:9,c_fill,g_auto,e_sharpen/v1642518198/vault-background-1_rkmvjz.jpg" alt="Vault tech background">
            {% endfor %}
        </div><!-- /.row -->
</div>

<a href="{% url 'BLOG:homepage' %}">
    <h2 class="btn btn-primary m-3 category-home">Back To Homepage</h2>
    </a>

{% endblock %}

templates/create_post.html
{% extends "base.html" %}
<title>Falloutinator | {% block title %}Create Blog Post{% endblock %}</title>

{% block content %}
{% if user.is_authenticated %}
<div class="create-container col-md-12">
    <h1 class="create-title">Create A Post...</h1>
    <div class="form-group create-form">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <button class="btn btn-primary post-btn" >Post</button>
        </form>
    </div>
</div>

<script>
    var username = "{{ user.id }}";
    document.getElementById("user1").value = username;
</script>

{% else %}
<h1>
You Must Sign Up To Create A Post
</h1>
<a href="{% url 'BLOG:homepage' %}">
    <h2 class="btn btn-primary">Back</h2>
    </a>
{% endif %}
{% endblock %}

templates/delete_post.html
{% extends "base.html" %}
<title>Falloutinator | {% block title %}Delete Blog Post{% endblock %}</title>

{% block content %}
<div class="delete-container">
{% if user.id == post.author.id %}
<h3 class="delete-title">Delete: {{ post.title }}</h3>
<div class="form-group">
    <form method="POST">
        {% csrf_token %}
        <p><small class="delete-warning">Are you sure you want to delete this post?</small></p>
        <button class="btn btn-primary m-3">Delete</button>
    </form>
    <a href="{% url 'BLOG:homepage' %}"><h2 class="btn btn-primary">Back</h2></a>
</div>
{% else %}
<h1>You Can't Delete Other's Posts. Naughty Naughty!!</h1>
<a href="{% url 'BLOG:homepage' %}"><h2 class="btn btn-primary">Back</h2></a>

{% endif %}
</div>
{% endblock %}

templates/edit_post.html
{% extends "base.html" %}
<title>Falloutinator | {% block title %}Edit Blog Post{% endblock %}</title>

{% block content %}
<div class="edit-container">
    {% if user.id == post.author.id %}
    <h1 class="edit-title">Edit Post...</h1>
    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <button class="btn btn-primary">Update</button>
        </form>
        <a href="{% url 'BLOG:homepage' %}"><h2 class="btn btn-primary mt-4">Back To Homepage</h2></a>
    </div>
    {% else %}
    <h1>You Can't Edit Other's Posts. Naughty Naughty!!</h1>
    <a href="{% url 'BLOG:homepage' %}"><h2 class="btn btn-primary mt-4">Back To Homepage</h2></a>
    {% endif %}
</div>
{% endblock %}

templates/edit_profile.html
{% extends "account/base.html" %}

{% load i18n %}

<title>Falloutinator | {% block title %}Contact Us {% endblock %}</title>

{% block content %}
<div class="contact-container">
    <h1 class="text-center">Contact Us</h1>
    <p class="text-center">Would you like to report someone? Delete your account or have any other issues?
        please get in touch via Email at <strong>benjaminjoe43@gmail.com</strong>
        I will respond within 24 hours
    </p>
    <a href="{% url 'BLOG:homepage' %}"> <h2 class="btn btn-primary detail-btn">Back</h2> </a>
</div>

{% endblock %}

templates/index.html
{% extends "base.html" %}
<title>Falloutinator | {% block title %}Home{% endblock %}</title>

{% block content %}
        <div class="container">
            <div class="row">
                    {% for post in postpage %}
                        <div class="col-lg-4 index-card">
                          {% if "placeholder" in post.post_image.url %}
                          <img class="rounded-circle index-img" src="https://res.cloudinary.com/benaldo66/image/upload/v1642635685/placeholder_lpvbw2.jpg" alt="Lazer background image with walls" width="140" height="140">
                          {% else %}
                          <img class="rounded-circle index-img" src="{{ post.post_image.url }}" alt="" width="140" height="140">
                          {% endif %}

                          <h2>{{ post.title|title }}</h2>
                          <p class="index-content">{{ post.content|striptags|slice:25}}...</p>
                          <p><small class="index-info">Written By: {{ post.author }} <br>
                          {{ post.created_on }} <br> {{ post.category }}</small></p>
                          <p><a class="btn btn-primary view-btn" href="{% url 'BLOG:post_detail' post.slug %}" role="button">View Post</a></p>
                          {% if user.id == post.author.id %}
                          <p><a class="btn btn-primary view-btn" href="{% url 'BLOG:EditPost' post.slug %}" role="button">Edit Post</a></p>
                          <p><a class="btn btn-primary view-btn" href="{% url 'BLOG:DeletePost' post.slug %}" role="button">Delete Post</a></p>
                          {% endif %}
                        </div>
                    {% endfor %}
                </div>
        </div>

        <hr>
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
        {% if postpage.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">&laquo  First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ postpage.previous_page_number }}">Previous</a></li>
        {% endif %}
        <li class="page-item disabled"><a href="#" class="page-link page-no">
        Page {{ postpage.number }} of {{ postpage.paginator.num_pages }}</a></li>
        {% if postpage.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ postpage.next_page_number }}">Next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ postpage.paginator.num_pages }}">Last &raquo;</a></li>
        {% endif %}
      </ul>
    </nav>
{% endblock %}

templates/news.html
{% extends "base.html" %}


{% block content %}
<title>{% block title %}News | {% endblock %}</title>
<div class="news-div">
    <div class="container px-4 py-2" id="featured-3">
    <h2 class="pb-2 border-bottom text-center">
        <img class="game-img-1" src="https://res.cloudinary.com/benaldo66/image/upload/v1638896045/fallout/game-w_f2jgyv.png" alt="Game-image">

        Keep Up With The Latest Fallout News
        <img class="game-img" src="https://res.cloudinary.com/benaldo66/image/upload/v1638896045/fallout/game-w_f2jgyv.png" alt="Game-image">
    </h2>
        <div class="row g-4 py-3 row-cols-1 row-cols-lg-3">
        <div class="feature col">
            <h2>Bethesda.net</h2>
            <p>Bethesda.net is the official website for all news related to Bethesdat games, including
            Fallout 3, Fallout New Vegas, Fallout 4 and Fallout 76. So what are you waiting for! 
            Click Below
            </p>
            <a href="https://fallout.bethesda.net/en" target="_blank" class="icon-link">
            Bethesda.net <i class="fas fa-forward"></i>
            </a>
        </div>

        <div class="feature col">
            <h2>Fallout.fandom</h2>
            <p>This is a great website for all things fallout. It doesn't matter if you are after new game news or where to find 
            the best weapons on the map! Fallout.fandom has it all. So put on your vault suit and click the link below!
            </p>
            <a href="https://fallout.fandom.com/wiki/Fallout_series" target="_blank" class="icon-link">
            Fallout.fandom <i class="fas fa-forward"></i>
            </a>
        </div>
        <div class="feature col">
            <div class="feature-icon bg-primary bg-gradient">
            </div>
            <h2>Fallout Reddit</h2>
            <p>Lookin for fellow vault dwellers? Then look no further than Reddit's Fallout page, from tips and tricks
            to finding fallout friends. Reddit has it all. Click the link below
            </p>
            <a href="https://www.reddit.com/r/Fallout/" target="_blank" class="icon-link">
            Fallout Reddit <i class="fas fa-forward"></i>
            </a>
        </div>
        </div>
    </div>

    <div class="container px-4 py-2" id="featured-3">
        <h2 class="pb-2 border-bottom text-center">Not Sure What To Write About?</h2>
        <p class="text-center"><small>Here Are A Few Conversation Starters! <br>
        Click Image Below For An Easter Egg!</small></p>
        <a target="_blank" href="https://www.digitaltrends.com/gaming/fallout-4-easter-eggs/">
        <img class="overlook-img" src="https://res.cloudinary.com/benaldo66/image/upload/v1638983812/fallout/stand-shad_dncwc1.png" alt="Overlooking powerline">
        </a>
        <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
        <div class="feature col">
            <div class="feature-icon bg-primary bg-gradient">
            <svg class="bi" width="1em" height="1em"><use xlink:href="#collection"/></svg>
            </div>
            <h2 class="text-center">Easter Eggs</h2>
            <p>What is your favorite easter egg across all Fallout games?
            It's hard to choose just one but for me it has to be Indiana Jones in a fridge in Fallout New Vegas! 
            A close second definitely has to be the toy sloth hanging off of the top of Mad Mulligan's Minecart Coaster in Fallout 4's 
            Nuka world DLC  </p>

        </div>
        <div class="feature col">
            <div class="feature-icon bg-primary bg-gradient">
            <svg class="bi" width="1em" height="1em"><use xlink:href="#people-circle"/></svg>
            </div>
            <h2 class="text-center">Favorite Game</h2>
            <p>Maybe write about your favorite Fallout game and start a debate about it? Me personally, it is between New Vegas
            and Fallout 4. I can already feel some fans getting angry reading that since New Vegas wasn't Bethesda and Fallout 4 
            had it's norotious bad dialogue choices. But that's just my opinion :) </p>

        </div>
        <div class="feature col">
            <div class="feature-icon bg-primary bg-gradient">
            <svg class="bi" width="1em" height="1em"><use xlink:href="#toggles2"/></svg>
            </div>
            <h2 class="text-center">Most Annoying NPC</h2>
            <p>Whilst there are a lot of great NPC in the Fallout games there are also a few not so great. Am I right Preston?
            For me peronally I choose Lily from Fallout New Vegas. Unpopular opinion I know, But she just got in the way all the time!
            </p>
        </div>
        </div>
    </div>

    <div class="container " id="featured-3">
        <div class="row g-4  row-cols-1 row-cols-lg-3">
        <div class="feature col">
            <div class="feature-icon bg-primary bg-gradient">
            <svg class="bi" width="1em" height="1em"><use xlink:href="#collection"/></svg>
            </div>
            <h2 class="text-center">Best Weapon</h2>
            <p>There are literally hundreds of weapons in the Fallout games, So lots to choose from. For me It would have to be either 
            the 2076 world series baseball bat, Just because of how fun it is to see enemies literally fly away or the gainer. Small, simple,
            effective, I like it.
            </p>
        </div>
        <div class="feature col">
            <div class="feature-icon bg-primary bg-gradient">
            <svg class="bi" width="1em" height="1em"><use xlink:href="#people-circle"/></svg>
            </div>
            <h2 class="text-center">Best DLC </h2>
            <p>For me, the answer is simple. I love big mountain! The old worls blues DLC blew my mind when I first played it. 
            The weapons, characters and just the layout of the map was like nothing I had ever seen before. The conclusion of the whole storyline
            was so bizzare and funny that it's something I will never forget!
            </p>

        </div>
        <div class="feature col">
            <div class="feature-icon bg-primary bg-gradient">
            <svg class="bi" width="1em" height="1em"><use xlink:href="#toggles2"/></svg>
            </div>
            <h2 class="text-center">Worst Quest</h2>
            <p>Putting the great quests to the side, lets focus on the bad ones. Fallout has had some questionable quests over ther years.
            I'm not a fan of follow me missions. But they are nothing compared to hearing the phrase, "Another settlement needs your help!" 
            If that's the case Preston, just do it yourself!
            </p>

        </div>
        </div>
    </div>
</div>
{% endblock %}

templates/post_detail.html
{% extends "base.html" %}
<title>Falloutinator | {% block title %}{{ post.title }}{% endblock %}</title>

{% block content %}

<div class="detail-card">
  <h1 class="detail-title">{{ post.title|title }}</h1>
  <h6 class="detail-author">Written By: {{ post.author }}</h6>
  <h6 class="detail-category">{{ post.category }}</h6>
  
  <form class="like-btn" action="{% url 'BLOG:like_post' post.slug %}" method="POST">
    {% csrf_token %}
    {% if user.is_authenticated %}
      {% if post.liked %}
      <h6><button class="far fa-thumbs-up btn btn-danger" type="submit" name="post_id" value="{{ post.id }}">{{ post.like_number }} Like(s)</button></h6>
      {% else %}
      <h6><button class="far fa-thumbs-up btn btn-primary" type="submit" name="post_id" value="{{ post.id }}">{{ post.like_number }} Like(s)</button></h6>
      {% endif %}
    {% else %}
    <h6 class="far fa-thumbs-up">
    {{ post.like_number }} Like(s)
    </h6>
    <p><a href="{% url 'account_signup' %}">Sign Up For Free To Like Posts</a></p>
    {% endif %}

  </form>


  <h6 class="detail-creted-on"><small>{{ post.created_on }}</small></h6>
  <div class="post-container">
  <p class="detail-content">{{ post.content|safe}}</p>
  </div>
  {% if "placeholder" in post.post_image.url %}
  <img class="detail-img" src="https://res.cloudinary.com/benaldo66/image/upload/v1642635685/placeholder_lpvbw2.jpg" alt="Lazer background image with walls">
  {% else %}
  <img class="detail-img" src="{{ post.post_image.url }}">
  {% endif %}
  {% if user.id == post.author.id %}
  <a class="btn btn-primary detail-btn" href="{% url 'BLOG:EditPost' post.slug %}" role="button">Edit Post</a>
  <a class="btn btn-primary detail-btn" href="{% url 'BLOG:DeletePost' post.slug %}" role="button">Delete Post</a>
  {% endif %}
  <a href="{% url 'BLOG:homepage' %}"> <h2 class="btn btn-primary detail-btn">Back</h2> </a>
</div>

<div class="comment-container col-md-12">
    {% with comments.count as total_comments %}
    <h1 class="comment-title">{{ total_comments }} Comment{{  total_comments|pluralize  }}</h1>
    {% endwith %}
    {% for comment in comments %}
    <div class="comment-div">
    <h5 class="comment-name">Comment By {{ comment.name }}:</h5>
    <p class="comment-content">{{ comment.content }}</p>
    </div>
    {% empty %}
    <h3 class="no-comment">No Comments Yet!</h3>
    {% endfor %}
    <h3 class="add-comment">Add A Comment Here</h3>

    <form id="comment_form" method="post">
        {% csrf_token %}
        <table class="comment-table">
        {{ comment_form.as_table }}
      </table>
      <button type="submit" class="btn btn-primary btn-block">Post Comment</button>

    </form>


    {% if user.is_authenticated %}
    {% if user.id == post.author.id %}
    <p><a class="btn btn-primary detail-btn-2" href="{% url 'BLOG:EditPost' post.slug %}" role="button">Edit Post</a></p>
    <p><a class="btn btn-primary detail-btn" href="{% url 'BLOG:DeletePost' post.slug %}" role="button">Delete Post</a></p>
    {% endif %}
    {% endif %}
</div>
{% endblock %}

templates/search_bar.html
{% extends "base.html" %}
<title>Falloutinator | {% block title %}{{ q }}{% endblock %}</title>

{% block content %}

<div class="container search-container">
    <div class="row">
        {% if q %}
        <h3 class="search-count">Blog Posts Containing "{{ q }}"</h3>
        {% with results.count as total_results %}
        <h4 class="result-count">
            We Found {{ total_results }} Object{{ total_results|pluralize }}
        </h4>
        {% endwith %}
            {% for post in results %}
                <div class="col-lg-4 index-card">
                  {% if "placeholder" in post.post_image.url %}
                  <img class="rounded-circle index-img" src="https://res.cloudinary.com/benaldo66/image/upload/v1642635685/placeholder_lpvbw2.jpg" alt="Lazer background image with walls" width="140" height="140">
                  {% else %}
                  <img class="rounded-circle index-img" src="{{ post.post_image.url }}" alt="" width="140" height="140">
                  {% endif %}
                  <h2>{{ post.title|title }}</h2>
                  <p class="index-content">{{ post.content|striptags|slice:25}}...</p>
                  <p><small class="index-info">Written By: {{ post.author }} <br>
                  {{ post.created_on }} <br> {{ post.category }}</small></p>
                  <p><a class="btn btn-primary view-btn" href="{{ post.get_absolute_url }}" role="button">View Post</a></p>
                </div>
                {% empty %}
                <h4 class="no-matches-search">No Matching Posts</h4>
            {% endfor %}
    {% endif %}
    </div>
</div>
{% endblock %}